### PR TITLE
feat: update graphhopper version to 1.0-pre18

### PR DESCRIPTION
**Pull request by develar**

### CODE REVIEW

**Comment by develar** [comment]
0.13.0 version has critical regressions regarding memory consumption during generating of routing files. 2 issues were fixed in 1.x pre-release versions (https://github.com/graphhopper/graphhopper/pull/1755 and https://github.com/graphhopper/graphhopper/pull/1809), so, I generated new files using `1.0-pre17` version.

So, I suggest to upgrade to 1.0-pre17 for this addon (I will add change soon),

**Comment by develar** [comment]
I do not have mobile phone to test for now, but at least compilable :) Will check today evening.
[app-addonGraphHopper-release.apk.zip](https://github.com/asamm/locus-addon-graphhopper/files/4096452/app-addonGraphHopper-release.apk.zip)

**Comment by develar** [comment]
Blocked on https://github.com/graphhopper/graphhopper/issues/1862

**Comment by menion** [comment]
Hello develar, 
thanks very much for the contribution!

Some time ago, I already made some changes in code & bigger conversion to Kotlin. Unfortunately, I wasn't able to make it work with GH 0.13 and I did not commit it.

Because of the inspiration of your PR (work with profiles & weightings), the app seems to run (I've not tested routing itself) now.

So, should be possible to update your code to the current state of separate dev branch [here](https://github.com/asamm/locus-addon-graphhopper/tree/dev/gh_0.13.0)? 

I think that only that needs to update is now the content in `setGraphHopperProperties` function. If you also add some comments about your changes, it will be very welcome.

Thanks and sorry for additional work!

**Comment by develar** [comment]
> So, should be possible to update your code to the current state of separate dev branch here?

Yes, I will do.

Currently it doesn't work, as described in https://github.com/graphhopper/graphhopper/issues/1862, I  am working on a solution (or my generated routing data is not correct, or new graphhopper version is too strict — not yet clear).

**Comment by jojojones** [comment]
I upgraded to 1.0 and does not work.
Screenshot_20200123-101057_Locus Map

**Comment by develar** [comment]
I found workaround — https://github.com/graphhopper/graphhopper/issues/1862#issuecomment-577839811 I tested and everything works as before, including street names. But it will take 24-72 hours to regenerate routing data. I will rebase PR tomorrow morning.

**Comment by develar** [comment]
PR rebased on your dev branch and merged with master (so, you can merge or squash into master easily).

Regarding Java to Kotlin convertation —  IntelliJ IDEA has option 

> If you use the Git commit dialog integrated with IntelliJ (Commit via Ctrl+K), there is a checkbox on the right in recent versions: ☑ Extra commit for .java > .kt renames

to preserve file history (or you can use https://github.com/develar/j2kt-commiter, but I didn't use since functionality was integrated into IntelliJ IDEA).  

Routing data not yet generated for all provided regions, but `Germany, Austria and Switzerland` / `Germany` / `Austria` / `Russia` are ready to use (any zip file that has modified data >= 24/01/2020 — https://d.graphhopper.develar.org/2019-01-21/?sort=time&order=desc).

**Comment by menion** [comment]
Perfect thanks. PR merged.

EDIT: btw, thanks for the tip with Kotlin conversion. Because I do not use integrated VCS in intelliJ, I never noticed this. Nice ...

**Comment by develar** [comment]
> Because I do not use integrated VCS in intelliJ

If you have any concern or unresolved issue in IntelliJ IDEA, feel free to contact me directly (I am from JetBrains, I can raise priority of some tasks or at least ask responsible developer in person).

All links on https://graphhopper.develar.org/ are valid (all data were regenerated).

**Comment by menion** [comment]
Ah, this is nice, thank you for offer and honor to communicate with someone who participates on such amazing tools :)

We are a little bit offtopic here but never mind. 

Currently, after two years, I've already converted around 49% of Locus Map/GIS code to Kotlin. It's currently somewhere around 150k lines of code so quite a lot for a single Android app.

The only big problem I had (and also rarely sometimes have), are incorrect conversions of parameters that do not have @nullable annotations and that are converted to non-null Kotlin types. To be true, not sure if the situation is better during the last months as currently, I write mostly new code, but I made me hard days :). Most of the core classes in AndroidX already have these annotations which makes life a lot easier.

Anyway > amazing work on the side of intelliJ :). And thanks for the help with GraphHopper as well!

**Comment by abelkov** [comment]
@menion Have you tried the new Java to Kotlin converter? It is specifically designed to infer the correct types in such cases: https://blog.jetbrains.com/kotlin/2019/08/kotlin-1-3-50-released/. Please give it a try. However, don't try to convert the entire project at once, because currently new J2K is not very well optimized for such cases: https://youtrack.jetbrains.com/issue/KT-31812.

**Comment by develar** [comment]
`Preferences | Languages & Frameworks | Kotlin`

Check `Use New Java to Kotlin Converter`.

Screenshot 2020-01-28 at 08 14 15

**Comment by menion** [comment]
Thanks guys. 
new converter, nice, by some accident I've missed this news, I'll give it a try, thank you!
And no worry, I always convert classes one-by-one. And most usually, because of the complexity of the whole project, function-by-function (into the second class).

**Comment by jojojones** [comment]
the 1 click download to get the data files in to locus still does not work but manually downloading them and placing them in maps/vector does work.
Screen Shot 2020-01-31 at 11 44 33 AM

**Comment by develar** [comment]
@jojojones Please specify for which region do you try to click on `Locus` link.

**Comment by jojojones** [comment]
US Northeast and US South both have error code as above.  1 click download does not work for me.

**Pull request merged**
